image: tetraweb/php

cache:
  paths:
  - httpdocs/bower_components/
  - vendor/

before_script:
- apt-get update -yqq
- apt-get install -yqq git unzip zlib1g-dev
- docker-php-ext-install zip
- curl -sS https://getcomposer.org/installer | php
- npm install -g bower

release:
  stage: deploy
  script:
  - php composer.phar install --no-dev
  - bower prune --allow-root
  - bower install --allow-root
  artifacts:
    paths:
    - bin/*.php
    - config
    - httpdocs
    - src
    - vendor
    - bootstrap.php
    - database.sql
    - LICENSE
    - README.md