cache:
  paths:
  - vendor/

before_script:
- apt-get update -yqq
- apt-get install -yqq git unzip zlib1g-dev
- docker-php-ext-install zip
- curl -sS https://getcomposer.org/installer | php

release:
  image: php:7.2
  stage: deploy
  script: php composer.phar install --no-dev
  artifacts:
    paths:
    - bin/*.php
    - config
    - httpdocs
    - src
    - vendor
    - bootstrap.php
    - database.sql
    - LICENSE
    - README.md